// frontend/src/components/SourcesPanel.tsx
import { useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import type { ApiClient } from "../lib/api";
import type { DocSummaryResponse, Hit } from "../lib/types";
import { wrapBareLatex } from "../lib/latex";
import { HitCard } from "./HitCard";

export interface SourceItem {
  num: number;
  hit: Hit;
}

export type PanelTab = "summary" | "chunks";

interface DocRef {
  docId: string;
  docName: string;
  nums: number[];
}

function distinctDocs(items: SourceItem[]): DocRef[] {
  const map = new Map<string, DocRef>();
  for (const { num, hit } of items) {
    const docId = hit.doc_id || hit.doc_name || `#${num}`;
    const existing = map.get(docId);
    if (existing) existing.nums.push(num);
    else
      map.set(docId, {
        docId,
        docName: hit.doc_name || hit.doc_id || "未知文献",
        nums: [num],
      });
  }
  return [...map.values()];
}

export function SourcesPanel({
  items,
  api,
  tab,
  onTabChange,
  highlightNum,
  highlightDocId,
  onClose,
}: {
  items: SourceItem[];
  api: ApiClient;
  tab: PanelTab;
  onTabChange: (t: PanelTab) => void;
  highlightNum?: number | null;
  highlightDocId?: string | null;
  onClose: () => void;
}) {
  const chunkRefs = useRef<Record<number, HTMLDivElement | null>>({});
  const docRefs = useRef<Record<string, HTMLDivElement | null>>({});
  const docs = distinctDocs(items);

  useEffect(() => {
    if (tab === "chunks" && highlightNum != null) {
      chunkRefs.current[highlightNum]?.scrollIntoView({
        behavior: "smooth",
        block: "center",
      });
    }
  }, [tab, highlightNum]);

  useEffect(() => {
    if (tab === "summary" && highlightDocId) {
      docRefs.current[highlightDocId]?.scrollIntoView({
        behavior: "smooth",
        block: "center",
      });
    }
  }, [tab, highlightDocId, docs.length]);

  return (
    <div className="flex h-full w-96 shrink-0 flex-col border-l border-slate-800 bg-slate-950/60">
      <div className="flex items-center justify-between border-b border-slate-800 px-4 py-2.5">
        <div className="flex gap-1">
          <TabBtn active={tab === "summary"} onClick={() => onTabChange("summary")}>
            文献简介 ({docs.length})
          </TabBtn>
          <TabBtn active={tab === "chunks"} onClick={() => onTabChange("chunks")}>
            引用块 ({items.length})
          </TabBtn>
        </div>
        <button
          onClick={onClose}
          className="rounded p-1 text-slate-400 hover:bg-slate-800 hover:text-slate-200"
          aria-label="关闭"
        >
          ✕
        </button>
      </div>

      <div className="flex-1 space-y-3 overflow-y-auto p-4">
        {items.length === 0 ? (
          <p className="mt-8 text-center text-sm text-slate-500">
            本次回答没有引用检索结果
          </p>
        ) : tab === "summary" ? (
          docs.map((d) => (
            <div
              key={d.docId}
              ref={(el) => {
                docRefs.current[d.docId] = el;
              }}
            >
              <DocSummaryCard
                api={api}
                docRef={d}
                highlight={highlightDocId === d.docId}
              />
            </div>
          ))
        ) : (
          items.map(({ num, hit }) => (
            <div
              key={num}
              ref={(el) => {
                chunkRefs.current[num] = el;
              }}
            >
              <HitCard hit={hit} num={num} highlight={highlightNum === num} />
            </div>
          ))
        )}
      </div>
    </div>
  );
}

function DocSummaryCard({
  api,
  docRef,
  highlight,
}: {
  api: ApiClient;
  docRef: DocRef;
  highlight?: boolean;
}) {
  const [data, setData] = useState<DocSummaryResponse | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let alive = true;
    setLoading(true);
    api
      .docSummary(docRef.docId)
      .then((d) => alive && (setData(d), setErr(null)))
      .catch((e) => alive && setErr(e instanceof Error ? e.message : String(e)))
      .finally(() => alive && setLoading(false));
    return () => {
      alive = false;
    };
  }, [api, docRef.docId]);

  return (
    <div
      className={`rounded-xl border bg-slate-900/60 p-3 text-sm transition ${
        highlight ? "border-blue-500 ring-1 ring-blue-500/50" : "border-slate-800"
      }`}
    >
      <div className="mb-1.5 flex items-start gap-2">
        <div className="flex flex-wrap gap-1">
          {docRef.nums.map((n) => (
            <span
              key={n}
              className="flex h-5 min-w-5 items-center justify-center rounded bg-blue-600/30 px-1 text-xs font-medium text-blue-200"
            >
              {n}
            </span>
          ))}
        </div>
        <span className="min-w-0 font-medium text-slate-200" title={docRef.docName}>
          {data?.title && data.title !== docRef.docId ? data.title : docRef.docName}
        </span>
      </div>

      {data?.year ? (
        <div className="mb-1.5 text-xs text-slate-400">{data.year} 年</div>
      ) : null}

      {loading ? (
        <p className="text-xs text-slate-500">加载简介中…</p>
      ) : err ? (
        <p className="text-xs text-rose-400">简介加载失败：{err}</p>
      ) : data?.summary ? (
        <div className="markdown leading-relaxed text-slate-300">
          <ReactMarkdown
            remarkPlugins={[remarkMath, remarkGfm]}
            rehypePlugins={[[rehypeKatex, { throwOnError: false, strict: false }]]}
          >
            {wrapBareLatex(data.summary)}
          </ReactMarkdown>
        </div>
      ) : (
        <p className="text-xs italic text-slate-500">（该文献暂无简介摘要）</p>
      )}
    </div>
  );
}

function TabBtn({
  active,
  onClick,
  children,
}: {
  active: boolean;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      onClick={onClick}
      className={`rounded-lg px-2.5 py-1 text-xs font-medium transition ${
        active
          ? "bg-blue-600/25 text-blue-200 ring-1 ring-blue-500/40"
          : "text-slate-400 hover:bg-slate-800 hover:text-slate-200"
      }`}
    >
      {children}
    </button>
  );
}

// frontend/src/components/SourcesPanel.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { NButton } from 'naive-ui'
import { useApi } from '@/composables/useApi'
import type { DocSummaryResponse, Hit } from '@/api/types'

export interface SourceItem {
  num: number
  hit: Hit
}

const props = defineProps<{
  items: SourceItem[]
  tab: 'summary' | 'chunks'
  highlightNum?: number | null
}>()
const emit = defineEmits<{
  (e: 'close'): void
  (e: 'update:tab', v: 'summary' | 'chunks'): void
}>()

const { t } = useI18n()
const api = useApi()
const summaries = ref<Record<string, DocSummaryResponse | 'loading' | 'error'>>({})

const docs = computed(() => {
  const seen = new Map<string, { num: number; hit: Hit }>()
  for (const it of props.items) {
    const key = it.hit.doc_id || it.hit.doc_name || String(it.num)
    if (!seen.has(key)) seen.set(key, it)
  }
  return [...seen.values()]
})

async function loadSummary(docId: string) {
  if (!docId || summaries.value[docId]) return
  summaries.value[docId] = 'loading'
  try {
    summaries.value[docId] = await api.docSummary(docId)
  } catch {
    summaries.value[docId] = 'error'
  }
}

watch(
  () => [props.tab, docs.value] as const,
  () => {
    if (props.tab === 'summary') {
      for (const d of docs.value) {
        const id = d.hit.doc_id || d.hit.doc_name
        if (id) loadSummary(id)
      }
    }
  },
  { immediate: true },
)
</script>

<template>
  <aside class="workspace-card ml-1 flex w-80 shrink-0 flex-col">
    <header class="flex items-center justify-between border-b border-softer px-4 py-3">
      <div class="flex items-center gap-1 text-sm">
        <NButton
          :tertiary="tab === 'summary'"
          :quaternary="tab !== 'summary'"
          size="tiny"
          @click="emit('update:tab', 'summary')"
        >
          {{ t('sources.summary') }}
        </NButton>
        <NButton
          :tertiary="tab === 'chunks'"
          :quaternary="tab !== 'chunks'"
          size="tiny"
          @click="emit('update:tab', 'chunks')"
        >
          {{ t('sources.chunks') }}
        </NButton>
      </div>
      <NButton quaternary circle size="small" :title="t('common.close')" @click="emit('close')">
        <template #icon>
          <span class="i-lucide-x" />
        </template>
      </NButton>
    </header>

    <div class="min-h-0 flex-1 overflow-y-auto p-3">
      <!-- 文献简介 -->
      <div v-if="tab === 'summary'" class="flex flex-col gap-2.5">
        <p v-if="docs.length === 0" class="py-8 text-center text-xs text-faint">{{ t('common.empty') }}</p>
        <div
          v-for="d in docs"
          :key="d.hit.doc_id || d.hit.doc_name || d.num"
          class="rounded-[8px] p-3 transition-colors"
          :class="highlightNum === d.num ? 'bg-accent-soft' : 'hover:bg-hover'"
        >
          <div class="flex items-start gap-2">
            <span class="cite-marker shrink-0">{{ d.num }}</span>
            <div class="min-w-0">
              <div class="truncate text-xs font-medium text-base" :title="d.hit.doc_name">
                {{ d.hit.doc_name || d.hit.doc_id }}
              </div>
              <template v-if="(d.hit.doc_id || d.hit.doc_name) && summaries[(d.hit.doc_id || d.hit.doc_name)!]">
                <p
                  v-if="summaries[(d.hit.doc_id || d.hit.doc_name)!] === 'loading'"
                  class="mt-1 text-xs text-faint"
                >
                  {{ t('common.loading') }}
                </p>
                <template v-else-if="typeof summaries[(d.hit.doc_id || d.hit.doc_name)!] === 'object'">
                  <div
                    class="mt-1 text-[11px] text-muted"
                  >
                    <span v-if="(summaries[(d.hit.doc_id || d.hit.doc_name)!] as DocSummaryResponse).year">
                      {{ t('sources.year', { n: (summaries[(d.hit.doc_id || d.hit.doc_name)!] as DocSummaryResponse).year }) }}
                    </span>
                  </div>
                  <p class="mt-1 line-clamp-6 text-xs leading-relaxed text-muted">
                    {{ (summaries[(d.hit.doc_id || d.hit.doc_name)!] as DocSummaryResponse).summary || t('sources.noSummary') }}
                  </p>
                </template>
              </template>
            </div>
          </div>
        </div>
      </div>

      <!-- 命中片段 -->
      <div v-else class="flex flex-col gap-2.5">
        <p v-if="items.length === 0" class="py-8 text-center text-xs text-faint">{{ t('common.empty') }}</p>
        <div
          v-for="it in items"
          :key="it.num"
          class="rounded-[8px] p-3 transition-colors"
          :class="highlightNum === it.num ? 'bg-accent-soft' : 'hover:bg-hover'"
        >
          <div class="mb-1 flex items-center gap-2">
            <span class="cite-marker shrink-0">{{ it.num }}</span>
            <span class="truncate text-xs font-medium text-base" :title="it.hit.doc_name">
              {{ it.hit.doc_name || it.hit.doc_id }}
            </span>
          </div>
          <div class="mb-1 flex flex-wrap gap-1 text-[10px] text-faint">
            <span v-if="it.hit.section" class="chip">{{ it.hit.section }}</span>
            <span v-if="it.hit.page_start != null" class="chip">{{ t('sources.page', { n: it.hit.page_start }) }}</span>
            <span v-if="it.hit.rerank_score != null" class="chip">{{ t('sources.rerank') }} {{ it.hit.rerank_score.toFixed(2) }}</span>
          </div>
          <p class="line-clamp-[12] whitespace-pre-wrap text-xs leading-relaxed text-muted">{{ it.hit.content }}</p>
        </div>
      </div>
    </div>
  </aside>
</template>
